compile:
	i386-elf-gcc -ffreestanding -m32 -g -c "stdio.cpp" -o "objects/stdio.o"
	i386-elf-gcc -ffreestanding -m32 -g -c "string.cpp" -o "objects/string.o"
	i386-elf-gcc -ffreestanding -m32 -g -c "hyeo.cpp" -o "objects/hyeo.o"